### ISSUE TITLE
Servers appear to be down again.

### ISSUE THREAD

**Issue by jayhawker6** [JordanPawlett/cards-against-formality#11]
![image](https://github.com/JordanPawlett/cards-against-formality/assets/75534911/772f9a2a-0b56-4802-af19-dedd3a163ba7)
This also appears:
![image](https://github.com/JordanPawlett/cards-against-formality/assets/75534911/4a040d9d-777a-4665-b422-3b7b01733437)
But I am not sure if that is the fault of 3rd party logins or implementation of them etc. All blockers turned off. This happens regardless logged in or not, and it cannot find any games and automatically goes to this page after failing. Attempting to retry does not fix the problem.

**Comment by JordanPawlett** [comment]
> ![image](https://private-user-images.githubusercontent.com/75534911/336177195-772f9a2a-0b56-4802-af19-dedd3a163ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDg4OTMsIm5iZiI6MTcxNzQ0ODU5MywicGF0aCI6Ii83NTUzNDkxMS8zMzYxNzcxOTUtNzcyZjlhMmEtMGI1Ni00ODAyLWFmMTktZGVkZDNhMTYzYmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDIxMDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNGVkOGQzZmZmNTU3YTVlM2IyMDkzM2Y1ZmNlMDE5YjMwYWNmYzY1YWU0NmIzNjEyODI2MWU2MzhjMDQ4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tS0tqOJFq5bnQw9qPpQhHn6MLZnNUow6-LHtcwIMO-g) This also appears: ![image](https://private-user-images.githubusercontent.com/75534911/336177459-4a040d9d-777a-4665-b422-3b7b01733437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDg4OTMsIm5iZiI6MTcxNzQ0ODU5MywicGF0aCI6Ii83NTUzNDkxMS8zMzYxNzc0NTktNGEwNDBkOWQtNzc3YS00NjY1LWI0MjItM2I3YjAxNzMzNDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDIxMDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODViMmNmZGFjNmVkZjViYWY5ODg4OGMyMjkwYTg4ZjAyNDRiOWQyNWIyNmM3Y2RiNzBmY2FlY2ExNDk3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLEvAi8RyY9EWtk6aGHFxNR8U2sti6rJkKuwph9Kjjg) But I am not sure if that is the fault of 3rd party logins or implementation of them etc. All blockers turned off. This happens regardless logged in or not, and it cannot find any games and automatically goes to this page after failing. Attempting to retry does not fix the problem.

Thank you for raising the issue. Servers were in the process of being migrated to reduce cost.
Full functionality should be restored now. Have fun! :smile:
