### ISSUE TITLE
severs are down 

### ISSUE THREAD

**Issue by Felco6416** [JordanPawlett/cards-against-formality#7]
trying to log in but it isn't allowing me to and I'm also unable to connect to anything

**Comment by ScythiaThe1st** [comment]
yeah you keep disconnecting everytime right?

**Comment by Felco6416** [comment]
I haven't checked in a while but when I went to play I went to find/create a room and it disconnected

**Comment by Felco6416** [comment]
Just check it's still doing it

**Comment by JordanPawlett** [comment]
@Felco6416 @CygnusThe1st the servers are back up now. My apologise. I run this on my own, and do not monetise the app in any way, so funding fell short for the server costs.
